---
- hosts: all
  become: yes

  tasks:
    - name: Gather information about installed packages
      package_facts:
        manager: apt

    - name: Install required packages if not present
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - apt-transport-https
        - ca-certificates
        - software-properties-common
      when: "{{ item }} not in ansible_facts.packages"

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker if not present
      apt:
        name: docker-ce
        state: present
      when: "'docker-ce' not in ansible_facts.packages"
