---
- hosts: all
  become: yes

  tasks:
    - name: Add Grafana Helm repository (if not already added)
      community.kubernetes.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts

    - name: Update Helm repositories
      community.kubernetes.helm_repository_update:

    - name: Install Grafana using Helm
      community.kubernetes.helm:
        name: grafana
        chart_ref: grafana/grafana
        namespace: monitoring
        values_file: "{{ playbook_dir }}/../../k8s/helm/values-grafana.yml"
