---
- hosts: all
  become: yes

  tasks:
    - name: Add Helm repository for stable charts
      kubernetes.core.helm_repository:
        name: stable
        repo_url: https://charts.helm.sh/stable

    - name: Install Helm chart
      kubernetes.core.helm:
        name: my_chart
        chart_ref: stable/my_chart
        namespace: default
