---
- hosts: all
  become: yes

  tasks:
    - name: Add Helm repository for stable charts
      community.kubernetes.helm_repository:
        name: stable
        repo_url: https://charts.helm.sh/stable

    - name: Update Helm repositories
      community.kubernetes.helm_repository_update:

    - name: Install Helm chart
      community.kubernetes.helm:
        name: my_chart
        chart_ref: stable/my_chart
        namespace: default
