---
- hosts: all
  become: yes

  tasks:
    - name: Install Helm (official repository)
      shell: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install -y apt-transport-https --no-install-recommends
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install -y helm
      args:
        executable: /bin/bash
      tags: install_helm

    - name: Add Helm repository for stable charts
      kubernetes.core.helm_repository:
        name: stable
        repo_url: https://charts.helm.sh/stable

    - name: Install Helm chart
      kubernetes.core.helm:
        name: my_chart
        chart_ref: stable/my_chart
        namespace: default
