---
- hosts: all
  become: yes

  tasks:
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      args:
        executable: /bin/bash

    - name: Verify Helm installation
      command: helm version
