---
- hosts: all
  become: yes

  tasks:
    - name: Install K3s
      xanmanning.k3s:
        k3s_version: 'v1.21.1+k3s1'

    - name: Copy kubeconfig to home directory
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0644'
