---
- hosts: all
  become: yes

  tasks:
    - name: Install K3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash

    - name: Set proper permissions for Kubeconfig
      shell: |
        chmod 644 /etc/rancher/k3s/k3s.yaml

    - name: Copy Kubeconfig to home directory
      shell: |
        mkdir -p {{ ansible_env.HOME }}/.kube
        cp /etc/rancher/k3s/k3s.yaml {{ ansible_env.HOME }}/.kube/config
        sudo chown $(id -u):$(id -g) {{ ansible_env.HOME }}/.kube/config
