---
- hosts: all
  become: yes

  roles:
    - role: xanmanning.k3s
      vars:
        k3s_version: 'v1.21.1+k3s1'

  tasks:
    - name: Copy kubeconfig to home directory
      become: yes
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0644'
