---
- hosts: all
  become: yes

  tasks:
    - name: Add Prometheus Helm repository (if not already added)
      community.kubernetes.helm_repository:
        name: prometheus
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Update Helm repositories
      community.kubernetes.helm_repository_update:

    - name: Install Prometheus using Helm
      community.kubernetes.helm:
        name: prometheus
        chart_ref: prometheus-community/prometheus
        namespace: monitoring
        values_file: "{{ playbook_dir }}/../../k8s/helm/values-prometheus.yml"
