---
- hosts: all
  become: yes

  tasks:
    - name: Add Prometheus Helm repository
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Update Helm repositories
      shell: helm repo update
      args:
        executable: /bin/bash

    - name: Install Prometheus using Helm
      shell: |
        helm install prometheus prometheus-community/prometheus \
        --namespace monitoring --create-namespace \
        --values {{ playbook_dir }}/../k8s/helm/values-prometheus.yml
      args:
        executable: /bin/bash
