apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    service:
      type: NodePort
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
    persistence:
      enabled: true
      size: 10Gi
    grafana.ini:
      auth:
        disable_login_form: false     # Keep the login form enabled for admin access
        allow_anonymous: true         # Enable anonymous access
      users:
        default_admin_user: admin     # Set the default admin username (can be changed as needed)
        default_admin_password: admin # Set the default admin password (change for security)
        auto_assign_org: true         # Automatically assigns anonymous users to the default organization
        auto_assign_org_role: Viewer  # Sets the role for anonymous users (Viewer access only)
