apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: "8.5.8"
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  values:
    # Customize Grafana's values here. Example:
    adminPassword: "admin"
    persistence:
      enabled: true
      size: 10Gi
    service:
      type: LoadBalancer # Can be ClusterIP or NodePort if you prefer
