apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    service:
      type: NodePort
      nodePort: 30091
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
    persistence:
      enabled: true
      size: 10Gi
    grafana.ini:
      metrics:
        enabled: true
      auth.anonymous:
        enabled: true
        org_name: Main Org.
        org_role: Admin # Viewer, Editor, Admin
