apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 1m
  chart:
    spec:
      chart: homeassistant
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: homeassistant
        namespace: flux-system
  values:
    service:
      type: NodePort
      ports:
        - port: 8123
          targetPort: 8123
          nodePort: 30092
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "250m"
        memory: "512Mi"
