apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m
  chart:
    spec:
      chart: pihole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    serviceWeb:
      type: NodePort
      ports:
        - name: metrics
          port: 9617
          targetPort: 9617
          nodePort: 30091
    serviceDns:
      type: NodePort
    serviceDhcp:
      type: NodePort
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
    pihole:
      TZ: "Europe/Paris"
      password: "Pedro1234"
    resources:
      requests:
        memory: "500Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9617"
