apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m
  chart:
    spec:
      chart: pihole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    service:
      type: NodePort
      nodePorts:
        dns: 30092
        http: 30093
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
    pihole:
      TZ: "Europe/Paris"
      adminPassword: "Pedro1234" # FIXME: not working, password is still default 'admin'
    resources:
      requests:
        memory: "500Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
