apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m
  chart:
    spec:
      chart: pihole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    serviceWeb:
      type: NodePort
      port: 82
      nodePort: 30082
    serviceDns:
      type: NodePort
      port: 53
      nodePort: 3053
    serviceDhcp:
      type: NodePort
      port: 67
      nodePort: 3067
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
    pihole:
      TZ: "Europe/Paris"
    admin:
      noPassword: true
      password: ""
    resources:
      requests:
        memory: "500Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
