apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m
  chart:
    spec:
      chart: pihole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
    service:
      type: NodePort
      web:
        enabled: true
        port: 80
        nodePort: 32001  # NodePort for Pi-hole web UI
      dns:
        tcp:
          enabled: true
          port: 53
          nodePort: 32002  # NodePort for DNS over TCP
        udp:
          enabled: true
          port: 53
          nodePort: 32003  # NodePort for DNS over UDP
      dhcp:
        enabled: true
        port: 67
        nodePort: 32004  # NodePort for DHCP (optional, only if using Pi-hole for DHCP)
    pihole:
      TZ: "Europe/Paris"
      WEBPASSWORD: "Pedro1234"
    resources:
      requests:
        memory: "500Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
