apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m
  chart:
    spec:
      chart: pihole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    serviceWeb:
      type: NodePort
      ports:
        - name: metrics
          port: 9617
          targetPort: 9617
          nodePort: 30091
    serviceDns:
      type: NodePort
      ports:
        - name: dns-tcp
          port: 53
          protocol: TCP
          targetPort: 53
          nodePort: 30092
        - name: dns-udp
          port: 53
          protocol: UDP
          targetPort: 53
          nodePort: 30092
    serviceDhcp:
      type: NodePort
      ports:
        - name: dhcp
          port: 67
          protocol: UDP
          targetPort: 67
          nodePort: 30093
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
    pihole:
      TZ: "Europe/Paris"
      adminPassword: "Pedro1234" # FIXME: not working, password is still default 'admin'
    resources:
      requests:
        memory: "500Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9617"
