apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m
  chart:
    spec:
      chart: pihole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
    service:
      type: NodePort
      web:
        enabled: true
      dns:
        tcp:
          enabled: true
        udp:
          enabled: true
      dhcp:
        enabled: true
    pihole:
      TZ: "Europe/Paris"
      WEBPASSWORD: "Pedro1234"
    resources:
      requests:
        memory: "500Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
