apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m
  chart:
    spec:
      chart: pihole
      version: "2.26.1"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
    service:
      type: NodePort
      web:
        port: 80
        nodePort: 32001
      dns:
        port: 53
        nodePort: 32002
    pihole:
      TZ: "Europe/Paris"
      WEBPASSWORD: "Pedro1234"
    resources:
      requests:
        memory: "500Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
