name: CI

on:
  push:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Kustomize
        run: |
          sudo apt-get install -y kustomize
          kustomize build clusters/my-cluster/
